# Generated by Django 2.1.15 on 2020-03-14 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('does', models.TextField(blank=True, max_length=10, null=True)),
                ('virtue', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('creator', models.CharField(max_length=60)),
                ('date', models.DateField(auto_now_add=True)),
                ('completed', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=60)),
                ('middle', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('last', models.CharField(max_length=60)),
                ('rank', models.CharField(choices=[('Cadet', 'Cadet'), ('2LT', '2LT'), ('1LT', '1LT'), ('CPT', 'CPT'), ('MAJ', 'MAJ'), ('LTC', 'LTC'), ('COL', 'COL'), ('BG', 'BG'), ('MG', 'MG'), ('LTG', 'LTG'), ('CIV', 'CIV')], max_length=5)),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True)),
                ('start', models.BigIntegerField(blank=True, null=True)),
                ('end', models.BigIntegerField(blank=True, null=True)),
                ('experiment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rater.Experiment')),
                ('name_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_1', to='rater.People')),
                ('name_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_2', to='rater.People')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rater', to='rater.People')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='rater.People')),
            ],
            options={
                'verbose_name_plural': 'results',
            },
        ),
        migrations.AddField(
            model_name='experiment',
            name='names',
            field=models.ManyToManyField(to='rater.People'),
        ),
        migrations.AddField(
            model_name='comments',
            name='experiment_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rater.Experiment'),
        ),
        migrations.AddField(
            model_name='comments',
            name='rater_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rater_name', to='rater.People'),
        ),
        migrations.AddField(
            model_name='comments',
            name='subject_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_name', to='rater.People'),
        ),
    ]
