# Generated by Django 2.1.15 on 2020-03-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='comment_type',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Virtues', 'Virtues'), ('None', 'None')], default='Standard', max_length=30),
        ),
        migrations.AddField(
            model_name='experiment',
            name='question',
            field=models.CharField(default='Select the better team member', max_length=60),
            preserve_default=False,
        ),
    ]
