# Generated by Django 2.1.15 on 2020-05-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0003_experiment_closeness_results_closeness'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='email',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
