# Generated by Django 2.1.15 on 2021-04-13 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0004_people_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments_Constructive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('experiment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rater.Experiment')),
                ('rater_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rater_name_const', to='rater.People')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_name_const', to='rater.People')),
            ],
            options={
                'verbose_name_plural': 'comments_constructive',
            },
        ),
    ]
