# Generated by Django 2.1.15 on 2021-04-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0005_comments_constructive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='question',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
