# Generated by Django 2.1.15 on 2022-06-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0006_auto_20210413_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='rank',
            field=models.CharField(choices=[('PVT', 'PVT'), ('PV2', 'PV2'), ('PFC', 'PFC'), ('SPC', 'SPC'), ('CPL', 'CPL'), ('SGT', 'SGT'), ('SSG', 'SSG'), ('SFT', 'SFT'), ('MSG', 'MSG'), ('1SG', '1SG'), ('SGM', 'SGM'), ('Cadet', 'Cadet'), ('2LT', '2LT'), ('1LT', '1LT'), ('CPT', 'CPT'), ('MAJ', 'MAJ'), ('LTC', 'LTC'), ('COL', 'COL'), ('BG', 'BG'), ('MG', 'MG'), ('LTG', 'LTG'), ('CIV', 'CIV')], max_length=5),
        ),
    ]
