# Generated by Django 2.1.15 on 2022-06-01 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0009_auto_20220601_1500'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='people',
            unique_together={('first', 'middle', 'last', 'rank', 'email')},
        ),
    ]
