# Generated by Django 2.1.15 on 2022-06-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0011_auto_20220601_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='per_complete',
            field=models.CharField(blank=True, default=0, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
