# Generated by Django 2.1.15 on 2022-06-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0013_final_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='final_results',
            name='names',
        ),
        migrations.AddField(
            model_name='final_results',
            name='names',
            field=models.ManyToManyField(to='rater.People'),
        ),
    ]
