# Generated by Django 2.1.15 on 2022-06-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0014_auto_20220610_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='final_results',
            name='experiment_name',
        ),
        migrations.RemoveField(
            model_name='final_results',
            name='names',
        ),
        migrations.DeleteModel(
            name='Final_Results',
        ),
    ]
