# Generated by Django 2.1.15 on 2022-06-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0016_final_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_results',
            name='score',
            field=models.DecimalField(decimal_places=5, max_digits=30),
        ),
    ]
