# Generated by Django 2.1.15 on 2022-06-14 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0017_auto_20220610_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='experiment_name',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='rater_name',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='subject_name',
        ),
        migrations.RemoveField(
            model_name='comments_constructive',
            name='experiment_name',
        ),
        migrations.RemoveField(
            model_name='comments_constructive',
            name='rater_name',
        ),
        migrations.RemoveField(
            model_name='comments_constructive',
            name='subject_name',
        ),
        migrations.RemoveField(
            model_name='experiment_closeness',
            name='names',
        ),
        migrations.RemoveField(
            model_name='results_closeness',
            name='experiment_name',
        ),
        migrations.RemoveField(
            model_name='results_closeness',
            name='name',
        ),
        migrations.RemoveField(
            model_name='results_closeness',
            name='rater',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='comment_type',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Comments_Constructive',
        ),
        migrations.DeleteModel(
            name='Experiment_Closeness',
        ),
        migrations.DeleteModel(
            name='Results_Closeness',
        ),
    ]
