# Generated by Django 3.2.13 on 2022-07-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0020_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='comments_at_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experiment',
            name='comments_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experiment',
            name='make_comments',
            field=models.BooleanField(default=False),
        ),
    ]
