# Generated by Django 2.1.15 on 2020-06-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey_Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=60)),
                ('response', models.CharField(max_length=60)),
                ('date', models.DateField(auto_now_add=True)),
                ('uuid', models.CharField(max_length=60)),
            ],
        ),
    ]
