# Generated by Django 2.1.15 on 2020-06-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey_results',
            options={'verbose_name_plural': 'Survey_Results'},
        ),
    ]
