# Generated by Django 2.1.15 on 2020-06-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyor', '0002_auto_20200626_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey_results',
            name='question',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='survey_results',
            name='response',
            field=models.CharField(max_length=500),
        ),
    ]
