# Generated by Django 2.1.15 on 2020-07-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyor', '0003_auto_20200626_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey_results',
            name='response',
            field=models.CharField(max_length=4000),
        ),
    ]
